version: '3'
services:
    contracts:
        image: "polyswarm/contractor"
        depends_on:
            - geth
            - sidechain
        environment:
            - geth=geth
            - sidechain=sidechain
        volumes:
            - "./:/build"
        command: ["./scripts/migrate_and_create_config.sh"]
